### ISSUE TITLE
Problem running MarkerSFM: No module named 'extract_metadata'

### ISSUE THREAD

**Issue by mpaffolter** [CogChameleon/MarkerSfM#1]
[setup_output.txt](https://github.com/CogChameleon/MarkerSfM/files/4127631/setup_output.txt)
The dependencies have been installed through the provided script. After running setup.py (output attached), I try to execute the run_markersfm.sh script and get this error:
```
adv@bootcamp:~/dev/MarkerSfM/scripts$ bash run_markersfm.sh /home/adv/dev/MarkerSfM/data/ece_floor4_wall/
===== Run MarkerSFM =====
=
= Running MarkerSFM

Traceback (most recent call last):
  File "../bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/adv/dev/MarkerSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
ModuleNotFoundError: No module named 'extract_metadata'
```
How can I check if the setup process was successful?
Note in setup.py output that vlfeat could not be built, but I am not sure if it is needed.
```
In file included from /home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.h:21,
                 from /home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:363:
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c: In function ‘_vl_kmeans_quantize_f’:
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/mathop.h:92:37: error: ‘vl_infinity_d’ not specified in enclosing ‘parallel’
   92 | #define VL_INFINITY_D (vl_infinity_d.value)
      |                       ~~~~~~~~~~~~~~^~~~~~~
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:685:34: note: in expansion of macro ‘VL_INFINITY_D’
  685 |       TYPE bestDistance = (TYPE) VL_INFINITY_D ;
      |                                  ^~~~~~~~~~~~~
In file included from /home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:1782:
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:672:9: error: enclosing ‘parallel’
  672 | #pragma omp parallel default(none) \
      |         ^~~
In file included from /home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:1788:
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c: In function ‘_vl_kmeans_quantize_d’:
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:685:27: error: ‘vl_infinity_d’ not specified in enclosing ‘parallel’
  685 |       TYPE bestDistance = (TYPE) VL_INFINITY_D ;
/home/adv/dev/MarkerSfM/opensfm/src/third_party/vlfeat/vl/kmeans.c:672:9: error: enclosing ‘parallel’
  672 | #pragma omp parallel default(none) \
```

**Comment by mpaffolter** [comment]
The problem was two-fold:
1. vlfeat needs to be built in order to produce csfm.so. Had to adjust the code like this to build it successfully (using gcc 9.2.1 on ubuntu 16.04):
https://github.com/colmap/colmap/commit/6af3d8b0048cecc3b9fc6f4e78c3214dd038180b
2. MarkerSfm and OpenSfm use python 2.7, so I used pyenv to install and switch to python 2.7 and rebuilt opengv to generate the correct python-bindings (in my case 2.7 instead of 3.6). Also, I created a symlink to the generated pyopengv.so in `~/.pyenv/versions/2.7.16/lib/python2.7/site-packages` so opengv module can be found.

Running the markersfm-pipeline on the example data now works :+1:

**Comment by yorklyb** [comment]
> The problem was two-fold:
> 
> 1. vlfeat needs to be built in order to produce csfm.so. Had to adjust the code like this to build it successfully (using gcc 9.2.1 on ubuntu 16.04):
>    [colmap/colmap@6af3d8b](https://github.com/colmap/colmap/commit/6af3d8b0048cecc3b9fc6f4e78c3214dd038180b)
> 2. MarkerSfm and OpenSfm use python 2.7, so I used pyenv to install and switch to python 2.7 and rebuilt opengv to generate the correct python-bindings (in my case 2.7 instead of 3.6). Also, I created a symlink to the generated pyopengv.so in `~/.pyenv/versions/2.7.16/lib/python2.7/site-packages` so opengv module can be found.
> 
> Running the markersfm-pipeline on the example data now works 👍

Hi. I'm wondering if you are still working on this.
