### ISSUE TITLE
Data Link cannot work

### ISSUE THREAD

**Issue by CarminLiu** [CogChameleon/MarkerSfM#4]
Hello, 

When I click the data link, it can't show the page. I wonder where can download the datasets, please.

Sorry for disturbing you.

**Comment by yuki-inaho** [comment]
I (probably) found the corresponding project page a few minutes ago.
And I downloaded the data from the below page. I hope this helps you, thanks.

http://www.josephdegol.com/pages/TagSfM_ECCV18.html

**Comment by CarminLiu** [comment]
> I (probably) found the corresponding project page a few minutes ago. And I downloaded the data from the below page. I hope this helps you, thanks.
> 
> http://www.josephdegol.com/pages/TagSfM_ECCV18.html

Thank you so much!!! 
It works!
